### ISSUE TITLE
getting pytz error

### ISSUE THREAD

**Issue by me0ne0** [dropbox/securitybot#21]
hello! i am a newbie. i was trying to implement security bot as my class assignment. I am getting the following error when i run main.py by following your guidelines

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from securitybot.bot import SecurityBot
  File "C:\securitybot-master\securitybot\bot.py", line 9, in <module>
    from securitybot.user import User
  File "C:\securitybot-master\securitybot\user.py", line 9, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

can u please help me?

**Comment by lxbrtsch** [comment]
You're getting this error because you haven't installed the module `pytz`. I suggest looking at the file `requirements.txt` in the repo. This file lists all the required modules for the package. I suggest reading [this documentation page](https://packaging.python.org/installing/) about installing modules.

**Comment by me0ne0** [comment]
thank you for your help
